name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Save SSH key to file
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key.pem
        chmod 600 /tmp/ssh_key.pem

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: /tmp/ssh_key.pem
        source: "."
        target: "/home/ubuntu/app"

    - name: Execute remote commands via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: /tmp/ssh_key.pem
        script: |
          cd /home/ubuntu/app
          docker-compose down
          docker-compose up -d --build
